name: 'Setup TeXLive'
description: 'Installs TeXLive packages'
inputs:
  requirements-file:  # id of input
    description: 'A list of packages to be installed'
    required: true
    default: '.github/texlive/requirements.txt'
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: sudo apt-get update -y || sudo apt-get update -y || sudo apt-get update -y
    - shell: bash
      run: sudo apt-get install -y texlive || sudo apt-get install -y texlive || sudo apt-get install -y texlive
    - shell: bash
      run: |
        if [ -f "${{ inputs.requirements-file }}" ]; then
          xargs -0 sudo apt-get install -y < <(tr \\n \\0 <"${{ inputs.requirements-file }}")
        fi
